import React, { useState, useEffect } from 'react';
import { EffectCoverflow, Autoplay } from 'swiper';
import { Swiper, SwiperSlide } from 'swiper/react';
import bannerList from '../../data/BannerList'

import { bannerPlaylistState } from '../../atoms/bannerAtom'
import { useRecoilState } from 'recoil'

import "swiper/css";
import "swiper/css/effect-coverflow";
import "swiper/css/effect-creative";
import "swiper/css/autoplay";
import "swiper/css/keyboard";

import useSWR from "swr";

const fetcher = (url) => fetch(url).then((res) => res.json());

/**
 * do not edit this file
 * swiper js image slider implementation here
 * with blur effect
 */

function ImageSlider({ textVisible }) {

    const [playlistState, setPlaylistState] = useRecoilState(bannerPlaylistState)

    const { data, error } = useSWR(
        "http://app.onthego.lk/api/public/v1/slider",
        fetcher
    );

    if (data) {
        setPlaylistState(data)
    }



    return (
        <>
            <div className='h-full hidden lg:inline'>
                {/* desktop view */}
                <Swiper className='swiper swiper-slide swiper-slide-active'
                    modules={[EffectCoverflow, Autoplay]}
                    effect={"coverflow"}
                    coverflowEffect={{
                        rotate: 0,
                        stretch: 0,
                        depth: 100,
                        modifier: 2,
                        slideShadows: true,
                    }}
                    keyboard={{
                        enabled: true,
                        onlyInViewport: true,
                    }}
                    centeredSlides={true}
                    loop={true}
                    // autoplay={{
                    //     delay: 5000,
                    //     disableOnInteraction: false,
                    // }}
                    slidesPerView={2}
                    onSlideChange={() => console.log('slide change')}
                    onSwiper={(swiper) => console.log(swiper)}
                >
                    {playlistState.map((item, index) => (
                        <SwiperSlide className='swiper-slide swiper-slide-active relative' key={index}>
                            <div key={index} className='h-full w-full'>
                                <img src={item.slider_image} alt="a" className='swiper-slide swiper-slide-active object-fill rounded-lg z-0' />
                                {textVisible
                                    ? <>
                                        <div className=' text-white h-full w-full bg-gradient-to-b from-[#110E1F] to-[#453598] opacity-30 absolute top-0 bottom-0 left-0 right-0 space-y-[10px]'></div>
                                        <div className=' text-white h-full w-full absolute top-0 bottom-0 left-0 right-0 space-y-3'>
                                            <div className='m-[5px]'><h1 className='text-[45px] font-bold '>{item.title}</h1></div>
                                            <div className='m-[5px]'><p className='text-[13px] font-medium truncate'>{item.description}</p></div>
                                        </div>
                                    </>
                                    : <></>
                                }
                            </div>
                        </SwiperSlide>
                    ))}
                </Swiper>
            </div>
            {/* mobile view */}
            <div className='h-full inline lg:hidden'>
                {/* mobile view */}
                <div className='mx-auto w-[280px] h-[175px] flex  overflow-x-scroll scrollbar-hide space-x-5 '>
                    {playlistState.map((item, index) => (
                        <div key={index} className='flex w-[250px] h-[175px] flex-shrink-0'>
                            <img src={item.slider_image} alt="a" className='swiper-slide swiper-slide-active object-fill rounded-lg z-0' />

                        </div>
                    ))}
                </div>
            </div>
        </>
    )
}

export default ImageSlider